# rules borrowed from GSA 
# https://github.com/GSA/odp-code-repository-commit-rules/blob/master/gitleaks/rules.toml

[[rules]]
	description = "IPv4 addresses"
	regex = '''[\W\D]?[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}[\W\D]?'''
	tags = ["IPv4", "IP", "addresses"]

[[rules]]
	description = "Slack API tokens"
	regex = '''xox.-[0-9]{12}-[0-9]{12}-[0-9a-zA-Z]{24}'''
	tags = ["key", "slack"]
