# rules borrowed from GSA 
# https://github.com/GSA/odp-code-repository-commit-rules/blob/master/gitleaks/rules.toml

[[rules]]
	description = "IPv4 addresses"
	regex = '''[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'''
	tags = ["IPv4", "IP", "addresses"]

[[rules]]
	description = "Social Security Numbers"
	regex = '''[0-9]{3}[\.\-][0-9]{2}[\.\-][0-9]{4}'''
	tags = ["SSN", "PII"]

[[rules]]
	description = "Credit Card Numbers"
	regex = '''[0-9]{12}(?:[0-9]{3})?'''
	tags = ["CreditCards", "PII"]

[[rules]] = "Slack API tokens"
	regex = '''xox.-[0-9]{12}-[0-9]{12}-[0-9a-zA-Z]{24}'''
	tags = ["key", "slack"]
